@echo off
echo Iniciando el Servidor Backend del Panel Central...
cd backend
call venv\Scripts\activate.bat
echo Creando tablas de la base de datos (si faltan)...
python create_db.py
echo Verificando usuario administrador...
python create_admin.py
echo Levantando Uvicorn...
uvicorn app.main:app --reload
pause
